# site
title: Phoemela Ballaran
url: "https://phoemelaballaran.github.io"
favicon: "/assets/icon-blue.png"
g_analytics: UA-12345678-1

# bio
header: PHOEMELA BALLARAN
desc: >
  
# posts
date_format: "%Y"
post_title: Post
post_date: Year
post_cat: Category

# post detail
prev-next: true

collections:
  experiments:
    output: true
    permalink: /:collection/:title

# experiments
date_format: "%Y"
project_title: Experiment
project_date: Year
project_cat: Category

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
